### ISSUE TITLE
document preview not working 

### ISSUE THREAD

**Issue by touchvignesh** [share-extras/wiki-rich-content#1]
![preview](https://f.cloud.github.com/assets/4943052/750576/2e6d4228-e4d1-11e2-9c3e-86401acf6f07.png)
![youtube](https://f.cloud.github.com/assets/4943052/750580/57c62d7e-e4d1-11e2-927d-d1fdce815a08.png)

Hi Wabson,

Thanks for the wonderful add-on. I pulled the latest code and created the jar file and deployed it in my latest 4.2.d code of alfresco. I made it the datalist, table, prettify to work with. 

Have few issues and glad if you can assist on it. 

The datalist having column date field is showing date in unformatted way i.e "2011-03-16T00:00:00.000Z"

And document preview is not working. When I enable it with both "Embed with link" and "Embed without link". It is showing as link only but not the preview. I tried with ppt, pdf etc.

Finally the youtube embed. It works only for some video and for some video its still showing "Error occurred" after clicking the play button. 
Note I have installed "media viewer " add-on. I pulled the latest code and created the jar file and deployed it.

Please let me know if I am missing something. Glad if you assist me in doing any further testing.

**Comment by wabson** [comment]
What browser do you see these issues on? I have no problem with document or YouTube embeds on Firefox or Chrome. I am testing against a 4.2.d nightly build.

**Comment by wabson** [comment]
Tested again on latest Wiki Rich Content / Media Viewers on 4.2 Enterprise. Document and video embeds still work fine. Closing issue as not reproducible.
