### ISSUE TITLE
Issue with Embed feature in 4.2e install

### ISSUE THREAD

**Issue by mosaicmedical** [share-extras/wiki-rich-content#3]
Went ahead and followed install instructions for this dashlet and am running into issues with doc embed and preview.

I have used the insert document link function then edited the link.  (had to save the wiki and edit before embed option was available) 

When I view wiki, I see only the link...no preview.

**Comment by wabson** [comment]
Which browser are you using?

Which modules did you enable?

Can you attach any screenshots which show the enabled modules and the problems that you are describing?

**Comment by wabson** [comment]
Closing due to lack of feedback
